site_name: scralenium
site_url: https://github.com/alexpdev/scralenium
repo_url: https://github.com/alexpdev/scralenium
site_description: "scralenium docs"
copyright: 2022-current

theme:
  name: material

nav:
  - xxxxx: xxxxx.md


plugins:
  - search
  - mkdocstrings

docs_dir: site
site_dir: docs
