<<<<<<< HEAD
site_name: TorrentFile
site_url: https://alexpdev.github.io/torrentfile
repo_url: https://github.com/alexpdev/torrentfile
site_description: "Bittorrent Meta File Creator."
copyright: alexpdev 2021
extra_css:
  - stylesheets/extra.css

theme:
  name: windmill
  logo: images/torrentfile.png
  favicon: images/favicon.png

nav:
  - home : index.md
  - API : api.md
  - Examples : examples.md
  - license : LGPLv3.md

plugins:
  - search
  - autorefs
  - mkapi
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: numpy
          rendering:
            show_root_heading: yes

docs_dir: site/
site_dir: docs/
=======
site_name: scralenium
site_url: https://github.com/alexpdev/scralenium
repo_url: https://github.com/alexpdev/scralenium
site_description: "scralenium docs"
copyright: 2022-current

theme:
  name: material

nav:
  - xxxxx: xxxxx.md


plugins:
  - search
  - mkdocstrings

docs_dir: site
site_dir: docs
>>>>>>> 82330a7980332da35d5c1048959db71f75cccaf6
