<template>
    <div class="tabs">
        <ul>
            <li class="is-active"><a href="">Torrent Creator</a></li>
            <li>Torrent Recheck</li>
            <li>Torrent Editor</li>
            <li>Torrent Info</li>
        </ul>
    </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import
export default defineComponent({
    name: "AppTabs",
    data() {
        return {

        }
    }
})
</script>
