name: CI

on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Setup Python
        uses: actions/setup-python@v4.1.0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox scrapy selenium coverage

      - name: Run tests and collect coverage
        run: |
          tox
          coverage run -m pytest tests
          coverage report
          coverage xml -o coverage.xml

      - name: Codecov
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml



      - name: Codacy Coverage Reporter
        uses: codacy/codacy-coverage-reporter-action@v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage.xml

      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4.1.0
